# Generated by Django 5.2.4 on 2026-03-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=24)),
                ('exchange', models.CharField(choices=[('NSE', 'NSE'), ('BSE', 'BSE'), ('CRYPTO', 'CRYPTO')], max_length=8)),
                ('order_type', models.CharField(choices=[('market', 'Market'), ('limit', 'Limit')], max_length=8)),
                ('action', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('limit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('executed', 'Executed'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('triggered', 'Triggered')], default='executed', max_length=10)),
                ('pnl', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
