# Generated by Django 5.2.4 on 2026-03-08 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingBotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('strategy', models.CharField(choices=[('ema_cross', 'EMA Cross (15m)')], default='ema_cross', max_length=20)),
                ('symbols', models.TextField(default='RELIANCE.NS,TCS.NS')),
                ('order_quantity', models.PositiveIntegerField(default=1)),
                ('poll_seconds', models.PositiveIntegerField(default=60)),
                ('max_daily_loss', models.DecimalField(decimal_places=2, default=500.0, max_digits=14)),
                ('max_open_positions', models.PositiveIntegerField(default=5)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bot_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TradingBotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warn', 'Warn'), ('error', 'Error')], default='info', max_length=10)),
                ('message', models.TextField()),
                ('symbol', models.CharField(blank=True, default='', max_length=24)),
                ('action', models.CharField(blank=True, default='', max_length=8)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
